version: 2
registries:
  npm-js:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_READ_TOKEN}}
    
version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tehran"
    registries: 
      - npm-js
