/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Devices {
  android_version: string | null;
  device_uuid: string;
  first_seen: Generated<Date>;
  id: Generated<number>;
  last_seen: Generated<Date>;
  model: string | null;
}

export interface NetworkLogs {
  cell_id: number | null;
  device_id: number;
  id: Generated<string>;
  latitude: number | null;
  longitude: number | null;
  network_type: string | null;
  plmn_id: string | null;
  /**
   * Reference Signal Received Power (for LTE)
   */
  rsrp: number | null;
  /**
   * Reference Signal Received Quality (for LTE)
   */
  rsrq: number | null;
  tac: number | null;
  timestamp: Date;
}

export interface TestConfigs {
  created_at: Generated<Date>;
  id: Generated<number>;
  interval_seconds: Generated<number>;
  is_enabled: Generated<number>;
  /**
   * e.g., URL for HTTP, phone number for SMS
   */
  target: string;
  test_type: "DNS" | "HTTP_DOWNLOAD" | "HTTP_UPLOAD" | "PING" | "SMS";
  updated_at: Generated<Date>;
}

export interface DB {
  devices: Devices;
  network_logs: NetworkLogs;
  test_configs: TestConfigs;
}
